---
- hosts: fileserver
  vars:
    test_ssh_key: 
  vars_files:
          - vars/vendors.yml
          - vars/admins.yml
          - vars/users.yml
          - vars/jslaves.yml
  tasks:
     - name: Install dependencies
       apt:
               name: "{{ item }}"
               state: present
       with_items:
               - acl

     - name: Create groups
       group:
               name: "{{ item }}"
               state: present
       with_items:
               - sftp_admin
               - "{{ vendors_list }}"
     
     - name: Create groups
       group:
               name: "jslave-{{ item }}"
               state: present
       with_items:
               - "{{ vendors_list }}"
    
     - name: Create jslave users
       user:
               name: "{{ item.name }}"
               shell: /bin/false
               groups: "jslave-{{ item.cgroup }}"
       with_items:
               - "{{ jslaves }}"

     - name: Add key to the jslaves authorized list
       authorized_key:
               user: "{{ item.name }}"
               state: present
               key: "{{ item.ssh_key }}"
       with_items:
               - "{{ jslaves }}"

     - name: Create admins
       user:
               name: "{{ item.name }}"
               shell: /bin/false
               groups: sftp_admin
       with_items:
               - "{{ admins }}"

     - name: Add key to the admins authorized list
       authorized_key:
               user: "{{ item.name }}"
               state: present
               key: "{{ item.ssh_key }}"
       with_items:
               - "{{ admins }}"
     
     - name: Create sftp users
       user:
               name: "{{ item.name }}"
               shell: /bin/false 
               groups: "{{ item.group }}"
       with_items:
               - "{{ users }}"
     
     - name: Add key to the users authorized list
       authorized_key:
               user: "{{ item.name }}"
               state: present
               key: "{{ item.ssh_key }}"
       with_items:
               - "{{ users }}"

     - name: Create repositories for results
       file:
               path: /var/results
               state: directory
               owner: root
               group: root

     - name: Set GID bit on the results dir
       shell: "chmod g+s /var/results"

     - name: Create each contained result directory
       file:
               path: "/var/results/{{ item }}"
               state: directory
               owner: root
               group: root
               mode: "770"
       with_items:
               - "{{ vendors_list }}"

     - name: Give proper ACL permissions
       acl:
               path: "/var/results/{{ item }}"
               entity: "{{ item }}"
               etype: group
               permissions: rx
               default: no
               state: present
       with_items:
               - "{{ vendors_list }}"

     - name: Give proper ACL permissions
       acl:
               path: "/var/results/{{ item }}"
               entity: "{{ item }}"
               etype: group
               permissions: r
               default: yes
               state: present
       with_items:
               - "{{ vendors_list }}"

     - name: Give proper ACL permissions
       acl:
               path: "/var/results/{{ item.cgroup }}"
               entity: "jslave-{{ item.cgroup }}"
               etype: group
               permissions: wx
               default: no
               state: present
       with_items:
               - "{{ jslaves }}"

     - name: Give proper ACL permissions
       acl:
               path: "/var/results/{{ item.cgroup }}"
               entity: "jslave-{{ item.cgroup }}"
               etype: group
               permissions: w
               default: yes
               state: present
       with_items:
               - "{{ jslaves }}"
     
     - name: Give proper ACL permissions
       acl:
               path: "/var/results/{{ item }}"
               entity: sftp_admin
               etype: group
               permissions: rwx
               default: no
               state: present
       with_items:
               - "{{ vendors_list }}"

     - name: Give proper ACL permissions
       acl:
               path: "/var/results/{{ item }}"
               entity: sftp_admin
               etype: group
               permissions: rwx
               default: yes
               state: present
       with_items:
               - "{{ vendors_list }}"

     - name: Copy sshd_config
       template:
               src: "./templates/sshd_config.j2"
               dest: "/etc/ssh/sshd_config"
               owner: root
               group: root
               mode: '0600'
               validate: /usr/sbin/sshd -t -f %s
               backup: yes

     - name: Restart ssh daemon
       shell: "systemctl restart sshd.service"


